### PR TITLE
Fixed Issues #40, #39, #38, and created F16_lab03.md file.

### PR DESCRIPTION
**Pull request by johnnyzhang1738**
Created the F16_lab03.md file for lab03 of cs56-f16.

### CODE REVIEW

**Comment by johnnyzhang1738** [comment]
I fixed issue #39 and @xosherry fixed issues #40 and #38. Issue #39 actually should only NOT save the game when the user has won or lost, it is OK if they have not placed any mines and want to save the game (same as the actual minesweeper settings).

**Comment by jimmylle** [comment]
@johnnyzhang1738 Hey Johnny, I'm playing the original version and the version with your updated code and I'm not sure what actually changed for the save functionality. Can you explain what changed?

**Comment by johnnyzhang1738** [comment]
Yeah. The save function should only be called when you haven't won or lost
a game. So for example if you open a mine, then close the pop-up dialog
box, and then go to main-menu, you will see that it doesn't save
the session wherein you lost the game.

**Comment by jimmylle** [comment]
> Yeah. The save function should only be called when you haven't won or lost
> a game. So for example if you open a mine, then close the pop-up dialog
> box, and then go to main-menu, you will see that it doesn't save
> the session wherein you lost the game.

If you play a game and then lose, a pop up dialog comes up with the choices reset game or main menu. What you're saying is that if I click on main menu on the pop up box it doesn't save the game or do you mean if I close the pop up box without clicking on one of the choices and then click on main menu on the top then it doesn't save the game.

**Comment by johnnyzhang1738** [comment]
It should work in both scenarios. I've only tested the way I described but
it should be ok in both

**Comment by jimmylle** [comment]
> It should work in both scenarios. I've only tested the way I described but
> it should be ok in both

The main menu button in the pop up box works, but I don't think the one at the top works. It still saves. Check if that's correct just in case for some reason mine's funky.

**Comment by johnnyzhang1738** [comment]
Ok I'll take a look when I get home.

**Comment by jimmylle** [comment]
> Ok I'll take a look when I get home.

Great, but don't work on any other issues besides this problem until I accept the pull request because I don't want to have you guys fix all your issues in one pull request, unless you guys fix the issues in a separate branch, then that's ok.

**Pull request merged**
